import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { run } from "../../src/core/pipeline.js";

const FIXTURE = resolve(__dirname, "../fixtures/Button.tsx");

describe("pipeline.run on Button.tsx", () => {
  it("extracts the component and props", async () => {
    const { model } = await run(FIXTURE);
    expect(model.name).toBe("Button");
    expect(model.props.map((p) => p.name).sort()).toEqual(
      ["disabled", "label", "onClick", "variant"].sort(),
    );
  });

  it("infers realistic default values", async () => {
    const { model } = await run(FIXTURE);
    expect(model.inferredValues.label?.expression).toBe('"Label"');
    expect(model.inferredValues.disabled?.expression).toBe("false");
    expect(model.inferredValues.variant?.expression).toBe('"primary"');
  });

  it("detects edge cases", async () => {
    const { model } = await run(FIXTURE);
    const ids = model.edgeCases.map((c) => c.id);
    expect(ids).toContain("disabled-true");
    expect(ids).toContain("variant-secondary");
    expect(ids).toContain("variant-danger");
  });

  it("produces deterministic output sources", async () => {
    const a = await run(FIXTURE);
    const b = await run(FIXTURE);
    expect(a.outputs.testSource).toBe(b.outputs.testSource);
    expect(a.outputs.storySource).toBe(b.outputs.storySource);
  });

  it("includes the review header in generated files", async () => {
    const { outputs } = await run(FIXTURE);
    expect(outputs.testSource).toContain("Generated by react-intel");
    expect(outputs.storySource).toContain("Generated by react-intel");
  });
});
