import type {ReactNode} from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import CodeBlock from '@theme/CodeBlock';

import HomepageFeatures from '@site/src/components/HomepageFeatures';

import styles from './index.module.css';

const installSnippet = `# Try it instantly with npx
npx react-spec-gen src/components/Button.tsx

# Or install as a dev dependency
npm install -D react-spec-gen`;

const componentSnippet = `// src/components/Button.tsx
type ButtonProps = {
  label: string;
  variant?: "primary" | "secondary";
  disabled?: boolean;
  onClick?: () => void;
};

export function Button({ label, variant = "primary", disabled, onClick }: ButtonProps) {
  return (
    <button disabled={disabled} onClick={onClick}>
      {label}
    </button>
  );
}`;

const testSnippet = `// Button.test.tsx — generated by react-spec-gen
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import { Button } from "./Button";

describe("Button", () => {
  const baseProps = {
    label: "Label",
    variant: "primary" as const,
    disabled: false,
    onClick: vi.fn(),
  };

  it("renders with default props", () => {
    render(<Button {...baseProps} />);
    expect(screen.getByRole("button")).toBeDefined();
  });

  it("when disabled is true", () => {
    const props = { ...baseProps, disabled: true };
    render(<Button {...props} />);
  });

  it("when variant is secondary", () => {
    const props = { ...baseProps, variant: "secondary" as const };
    render(<Button {...props} />);
  });
});`;

const storySnippet = `// Button.stories.tsx — generated by react-spec-gen
import type { Meta, StoryObj } from "@storybook/react";
import { Button } from "./Button";

const meta: Meta<typeof Button> = {
  title: "Components/Button",
  component: Button,
};
export default meta;

type Story = StoryObj<typeof Button>;

export const Default: Story = {
  args: { label: "Label", variant: "primary" },
};

export const Secondary: Story = {
  args: { label: "Label", variant: "secondary" },
};

export const Disabled: Story = {
  args: { label: "Label", disabled: true },
};`;

function HomepageHeader() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <header className={clsx(styles.heroBanner)}>
      <div className={clsx('container', styles.heroInner)}>
        <span className={styles.eyebrow}>v0.1.2 · MIT · Node ≥ 20</span>
        <Heading as="h1" className={styles.heroTitle}>
          {siteConfig.title}
        </Heading>
        <p className={styles.heroTagline}>{siteConfig.tagline}</p>
        <div className={styles.buttons}>
          <Link
            className="button button--primary button--lg"
            to="/docs/getting-started">
            Get started
          </Link>
          <Link
            className="button button--secondary button--lg"
            to="/docs/intro">
            Read the docs
          </Link>
          <Link
            className={clsx('button button--lg', styles.ghostButton)}
            href="https://github.com/matieydjato/react-intel">
            GitHub →
          </Link>
        </div>

        <div className={styles.installBox}>
          <CodeBlock language="bash">{installSnippet}</CodeBlock>
        </div>
      </div>
    </header>
  );
}

function ShowcaseSection() {
  return (
    <section className={styles.showcase}>
      <div className="container">
        <div className={styles.showcaseHeader}>
          <Heading as="h2">From component to test + story in one command</Heading>
          <p>
            react-spec-gen statically analyzes your React component, infers
            realistic prop values, and writes a Vitest test file and a
            Storybook CSF 3 story right next to the source.
          </p>
        </div>

        <div className={styles.showcaseGrid}>
          <div>
            <h3 className={styles.showcaseLabel}>Your component</h3>
            <CodeBlock language="tsx" title="Button.tsx">
              {componentSnippet}
            </CodeBlock>
          </div>
          <div>
            <h3 className={styles.showcaseLabel}>Generated test</h3>
            <CodeBlock language="tsx" title="Button.test.tsx">
              {testSnippet}
            </CodeBlock>
          </div>
          <div className={styles.fullSpan}>
            <h3 className={styles.showcaseLabel}>Generated story</h3>
            <CodeBlock language="tsx" title="Button.stories.tsx">
              {storySnippet}
            </CodeBlock>
          </div>
        </div>
      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section className={styles.cta}>
      <div className="container">
        <Heading as="h2">Ready to remove test boilerplate?</Heading>
        <p>
          Run it once on a component. Review the verification checklist. Commit.
        </p>
        <div className={styles.buttons}>
          <Link
            className="button button--primary button--lg"
            to="/docs/getting-started">
            Get started in 2 minutes
          </Link>
          <Link
            className="button button--secondary button--lg"
            to="/docs/cli">
            View CLI reference
          </Link>
        </div>
      </div>
    </section>
  );
}

export default function Home(): ReactNode {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout
      title={`${siteConfig.title} — ${siteConfig.tagline}`}
      description="Auto-generate Vitest + React Testing Library tests and Storybook CSF 3 stories from your React components. Offline, deterministic, with optional AI enhancement.">
      <HomepageHeader />
      <main>
        <HomepageFeatures />
        <ShowcaseSection />
        <CTASection />
      </main>
    </Layout>
  );
}
