// Generated by react-intel — review before committing.
import type { Meta, StoryObj } from "@storybook/react";
import { Button } from "./Button";

const meta: Meta<typeof Button> = {
  title: "Components/Button",
  component: Button,
};
export default meta;

type Story = StoryObj<typeof Button>;

export const Default: Story = {
  args: {
    label: "Submit",
    variant: "primary",
    disabled: false,
    onClick: () => {},
  },
};

export const VariantSecondary: Story = {
  args: {
    ...Default.args,
    variant: "secondary",
  },
};

export const VariantDanger: Story = {
  args: {
    ...Default.args,
    variant: "danger",
  },
};

export const DisabledTrue: Story = {
  args: {
    ...Default.args,
    disabled: true,
  },
};

export const LabelLongText: Story = {
  args: {
    ...Default.args,
    label: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  },
};
