// Generated by react-intel — review before committing.
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import { Button } from "./Button";

describe("Button", () => {
  const baseProps = {
    label: "Submit",
    variant: "primary",
    disabled: false,
    onClick: vi.fn(),
  };

  it("renders with default props", () => {
    render(<Button {...baseProps} />);
    expect(screen.getByRole("button")).toBeDefined();
  });

  it("when variant is secondary", () => {
    const props = {
      ...baseProps,
      variant: "secondary",
    };
    render(<Button {...props} />);
  });

  it("when variant is danger", () => {
    const props = {
      ...baseProps,
      variant: "danger",
    };
    render(<Button {...props} />);
  });

  it("when disabled is true", () => {
    const props = {
      ...baseProps,
      disabled: true,
    };
    render(<Button {...props} />);
  });

  it("when label contains a very long string", () => {
    const props = {
      ...baseProps,
      label: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    };
    render(<Button {...props} />);
  });
});
