// Generated by react-spec-gen — review before committing.
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import Hero from "./Hero";

describe("Hero", () => {
  const baseProps = {
    bgType: "image",
    bg: "Bg",
    backDropBg: "linear-gradient(180deg, rgba(1, 1, 1, 0.5) 0%, rgba(1, 1, 1, 0.7) 100%)",
    children: "Children",
  } as const;

  it("renders with default props", () => {
    render(<Hero {...baseProps} />);
    expect(document.body.firstChild).not.toBeNull();
  });

  it("when bgType is video", () => {
    const props = {
      ...baseProps,
      bgType: "video",
    } as const;
    render(<Hero {...props} />);
  });

  it("when backDropBg is an empty string", () => {
    const props = {
      ...baseProps,
      backDropBg: "",
    } as const;
    render(<Hero {...props} />);
  });

  it("when children is undefined", () => {
    const props = {
      ...baseProps,
      children: undefined,
    } as const;
    render(<Hero {...props} />);
  });
});
