// Generated by react-intel — review before committing.
import type { Meta, StoryObj } from "@storybook/react";
import Hero from "./Hero";

const meta: Meta<typeof Hero> = {
  title: "Components/Hero",
  component: Hero,
};
export default meta;

type Story = StoryObj<typeof Hero>;

export const Default: Story = {
  args: {
    bgType: "image",
    bg: "Bg",
    backDropBg: "linear-gradient(180deg, rgba(1, 1, 1, 0.5) 0%, rgba(1, 1, 1, 0.7) 100%)",
    children: "Children",
  },
};

export const BgTypeVideo: Story = {
  args: {
    ...Default.args,
    bgType: "video",
  },
};

export const BackDropBgEmpty: Story = {
  args: {
    ...Default.args,
    backDropBg: "",
  },
};

export const ChildrenUndefined: Story = {
  args: {
    ...Default.args,
    children: undefined,
  },
};
