// Generated by react-intel — review before committing.
import type { Meta, StoryObj } from "@storybook/react";
import { Input } from "./Input";

const meta: Meta<typeof Input> = {
  title: "Components/Input",
  component: Input,
};
export default meta;

type Story = StoryObj<typeof Input>;

export const Default: Story = {
  args: {
    value: "Value",
    placeholder: "Placeholder",
    maxLength: 1,
    onChange: () => {},
    hint: "Hint",
  },
};

export const PlaceholderEmpty: Story = {
  args: {
    ...Default.args,
    placeholder: "",
  },
};

export const PlaceholderUndefined: Story = {
  args: {
    ...Default.args,
    placeholder: undefined,
  },
};

export const MaxLengthUndefined: Story = {
  args: {
    ...Default.args,
    maxLength: undefined,
  },
};

export const HintUndefined: Story = {
  args: {
    ...Default.args,
    hint: undefined,
  },
};
