// Generated by react-spec-gen — review before committing.
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import { Input } from "./Input";

describe("Input", () => {
  const baseProps = {
    value: "Value",
    placeholder: "Placeholder",
    maxLength: 1,
    onChange: vi.fn(),
    hint: "Hint",
  };

  it("renders with default props", () => {
    render(<Input {...baseProps} />);
    expect(document.body.firstChild).not.toBeNull();
  });

  it("when placeholder is an empty string", () => {
    const props = {
      ...baseProps,
      placeholder: "",
    };
    render(<Input {...props} />);
  });

  it("when placeholder is undefined", () => {
    const props = {
      ...baseProps,
      placeholder: undefined,
    };
    render(<Input {...props} />);
  });

  it("when maxLength is undefined", () => {
    const props = {
      ...baseProps,
      maxLength: undefined,
    };
    render(<Input {...props} />);
  });

  it("when hint is undefined", () => {
    const props = {
      ...baseProps,
      hint: undefined,
    };
    render(<Input {...props} />);
  });
});
